# Generated by Django 3.1.1 on 2021-09-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_table',
            name='price',
            field=models.IntegerField(),
        ),
    ]
