# Generated by Django 3.1.1 on 2021-10-06 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminapp', '0003_auto_20210927_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_table',
            name='display_type',
            field=models.CharField(choices=[('Feature product', 'Feature product'), ('Category product', 'Category product'), ('None', 'None')], default=None, max_length=20),
        ),
        migrations.CreateModel(
            name='Order_table',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_purchased', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField()),
                ('price', models.CharField(max_length=11)),
                ('purchased', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.product_table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
