# Generated by Django 3.1.1 on 2021-10-05 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_auto_20211006_1059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_table',
        ),
    ]
